# Generated by Django 5.1.5 on 2025-01-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='img_url',
            new_name='image_url',
        ),
        migrations.AlterModelTable(
            name='destination',
            table='destinations',
        ),
    ]
