from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TripView

# Create a router and register the viewset
router = DefaultRouter()
router.register(r'', TripView, basename='trip')  # Register the TripView with the router

# Include the router's URLs
urlpatterns = [
    path('', include(router.urls)),  # Includes all routes generated by the router
]
